version: '3'

services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        links:
            - db
        environment:
            #Environment variables for database connection
            - MYSQL_HOST=db
            - MYSQL_DATABASE=mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - FLASK_APP=app.py
            - FLASK_RUN_HOST=0.0.0.0
            - TZ=Asia/Jerusalem

    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Asia/Jerusalem
        volumes:
            - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        ports:
            - "33000:3306"

